# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SEOWebChecker.SEOWebChecker
PackageVersion: 1.0.1
Platform:
- Windows.Desktop
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: seowebchecker.exe
  PortableCommandAlias: seowebchecker
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jaiganesh6999/seowebchecker-seoaudit-sdk/releases/download/v1.0.1/seowebchecker-windows-x64.zip
  InstallerSha256: 4F7BFF1CA7AA52A74530F7C470DC5F3EF1488B54DE718D3CF80A48BECC0E590F
ManifestType: installer
ManifestVersion: 1.6.0
